### ISSUE TITLE
Add legend for colour scale

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/risk-maps#12]
<img width="725" alt="Screenshot 2020-04-03 at 13 39 51" src="https://user-images.githubusercontent.com/600993/78356827-9ef87b80-75b0-11ea-86ee-f19d3409ce55.png">

It is unclear what those colours represent. A legend should be added, with a unit and values.

**Comment by niconoe** [comment]
Indeed, will do after implementing the proper color scale (#2).

**Comment by niconoe** [comment]
Update: There's now a basic legend, comments welcome!

**Comment by peterdesmet** [comment]
Nice, but the unit is not indicated. 😄

**Comment by niconoe** [comment]
Indeed! 

@amyjsdavis, what unit should I show? I understand 0 means "no risk at all" and 100 means 100% certainty, would it be better for end-users if we multiply the value by 100 and present them as percent?

@soVDH, maybe you also have an opinion on this?

**Comment by amyjsdavis** [comment]
@niconoe : yes you are interpreting risk correctly, although in reality there are rarely places that are 0 or 100% risk.  Hmm, the convention is show the scale on 0-1, or using the lowest and highest risk as the scale bounds (ie. .005 and .995), but perhaps using percents is more intuitive. I will default to the wisdom of @SoVDH.

**Comment by SoVDH** [comment]
I would suggest showing a range from (0-no risk) to (1 high-risk) for risk maps and (0-low uncertainty) to (1-high uncertainty) for uncertainty maps. Percentage are perceived and interpreted differently from a user to another. Risk communication literature suggests to avoid the use of percentage because if refers to relative risks. 
Does this sounds ok to you @amyjsdavis ?

**Comment by amyjsdavis** [comment]
@SoVDH : that makes sense and is fine by me!

**Comment by niconoe** [comment]
Implemented
